### ISSUE TITLE
DRAKON diagram support

### ISSUE THREAD

**Issue by qjcg** [terrastruct/d2#1066]
Would the d2 project ever consider supporting DRAKON diagrams?

As far as I know, no other text-to-diagram tool currently supports this powerful diagram type, so this could be a strong differentiator. DRAKON diagrams are intended for clearly representing any process that has a goal --- so great for representing computing algorithms, business processes, health care procedures, etc.

# Resources

- [The DRAKON Language](https://drakonhub.com/drakon)
- [Learn DRAKON by Example](https://drakonhub.com/drakon-examples)
- [DRAKON Language Reference](https://drakonhub.com/drakon-reference)
- [Try a DRAKON flowchart in the browser](https://drakonhub.com/start-drakon)
- [Visual Syntax of the DRAKON Language](https://drakon.su/_media/video_i_prezentacii/graphical_syntax_.pdf)
- Video - DRAKON: Flowcharts that have order 
  - [Part 1/2: Primitives](https://www.youtube.com/watch?v=j-M_z_7_Nkw)
  - [Part 2/2: Silhouette](https://www.youtube.com/watch?v=Q0YBdX9xazw)

**Comment by alixander** [comment]
hmm this would require new shapes and a new layout algorithm for this specific flowchart. i'm not opposed if someone wants to try the algorithm part using just boxes (it'd be a special layout algorithm like sequence_diagram). But it's not popular enough for the core team to spend time on it over all the other things. 

if someone comes along and wants to try this, please ping me. I'll reopen and help guide you.

**Comment by qjcg** [comment]
@alixander I'm open to working on a "box-only-prototype" for this. I'm already a big user of d2, and it's a nice opportunity to contribute.

**Comment by qjcg** [comment]
> Is Drakon rule-based like sequence diagrams are?

Broadly, yes, for example (via the Resources I listed above):

- Time flows downwards; branching goes to the right
- Lines are not allowed to cross
- Only straight lines and right angles are allowed
- Arrows are replaced with plain lines
- The happy path goes straight downwards ("the further to the right, the worse")
- Horizontally aligned items must have the same width
- Outcomes of a conditional should be vertically aligned to indicate "common fate"

> Can you lay out a rough plan of implementation? And then I'll help point you to places in the code and we can work out a design for a v1 together.

Sounds good! A rough plan follows:

# Implementation Plan

The items below are high level and should probably be completed in descending order.

- [ ] draft of D2 Syntax
  - Create an initial draft of proposed d2 syntax. I agree that starting with `shape: drakon` indeed could work for this. Should be fairly comprehensive (e.g. cover both primitive and silhouette diagram types, as well as branching of various types (e.g. question, choice, input/output parameters, timers, ...).
- [ ] primitive (non-branching)
  - implement basic non-branching skewer / happy path (using boxes to represent: start/end, actions, comments, insertion, for loop, ...)
- [ ] primitive (branching)
  - implement branching elements on a primitive (e.g. question, choice, concurrent process, ...)
- [ ] silhouette
  - implement the silhouette diagram type (basically, groups together primitives as described above)
- [ ] add DRAKON language shapes (e.g. see [here](https://drakonhub.com/drakon-reference))

Feedback welcome!

> Nothing else in the semantics needs to change I don't believe, as it's just a way of laying out flowcharts right.

I think that may indeed be right, but working through the plan above will allow us to confirm that one way or another.

**Comment by sh4r1k7** [comment]
Hey guys, this is marked "completed" but I cannot find any work on this - was the prototype implemented?

**Comment by alixander** [comment]
It was not, marking as closed incomplete instead
